CREATE TABLE payments (
                          id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          reference      VARCHAR2(100) NOT NULL UNIQUE,
                          from_wallet_id NUMBER(19) NOT NULL,
                          to_wallet_id   NUMBER(19),
                          to_iban        VARCHAR2(34),
                          type           VARCHAR2(20) NOT NULL,
                          status         VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
                          amount         NUMBER(19,4) NOT NULL,
                          currency       VARCHAR2(3) NOT NULL,
                          created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);