CREATE TABLE external_transfers (
                          id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          reference      VARCHAR2(100) NOT NULL UNIQUE,
                          to_iban        VARCHAR2(34),
                          amount         NUMBER(19,4) NOT NULL,
                          currency       VARCHAR2(3) NOT NULL,
                          status         VARCHAR2(10) NOT NULL,
                          created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);