CREATE TABLE accounts (
                          id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          user_id     NUMBER(19) NOT NULL,
                          iban        VARCHAR2(34) NOT NULL UNIQUE,
                          status      VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
                          created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE wallets (
                         id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         account_id  NUMBER(19) NOT NULL,
                         currency    VARCHAR2(3) NOT NULL,
                         balance     NUMBER(19,4) DEFAULT 0 NOT NULL,
                         created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         CONSTRAINT fk_wallet_account FOREIGN KEY (account_id) REFERENCES accounts(id),
                         CONSTRAINT uq_wallet_acc_ccy UNIQUE (account_id, currency)
);