CREATE TABLE ledger_accounts (
                                 id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 account_ref  NUMBER(19),
                                 currency     VARCHAR2(3) NOT NULL,
                                 type         VARCHAR2(20) NOT NULL,
                                 created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE journal_entries (
                                 id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 reference    VARCHAR2(100) NOT NULL UNIQUE,
                                 description  VARCHAR2(255),
                                 created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE postings (
                          id                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          journal_entry_id   NUMBER(19) NOT NULL,
                          ledger_account_id  NUMBER(19) NOT NULL,
                          direction          VARCHAR2(6) NOT NULL,
                          amount             NUMBER(19,4) NOT NULL,
                          created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          updated_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          CONSTRAINT fk_posting_entry   FOREIGN KEY (journal_entry_id)  REFERENCES journal_entries(id),
                          CONSTRAINT fk_posting_account FOREIGN KEY (ledger_account_id) REFERENCES ledger_accounts(id)
);