ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER userkyc IDENTIFIED BY userkyc_2026;
GRANT CONNECT, RESOURCE TO userkyc;
ALTER USER userkyc QUOTA UNLIMITED ON USERS;

CREATE USER accountsvc IDENTIFIED BY accountsvc_2026;
GRANT CONNECT, RESOURCE TO accountsvc;
ALTER USER accountsvc QUOTA UNLIMITED ON USERS;

CREATE USER ledgersvc IDENTIFIED BY ledgersvc_2026;
GRANT CONNECT, RESOURCE TO ledgersvc;
ALTER USER ledgersvc QUOTA UNLIMITED ON USERS;