CREATE TABLE users (
                       id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       full_name   VARCHAR2(255) NOT NULL,
                       username    VARCHAR2(100) NOT NULL UNIQUE,
                       email       VARCHAR2(255) NOT NULL UNIQUE,
                       phone       VARCHAR2(30),
                       kyc_status  VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
                       created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                       updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE kyc_documents (
                               id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id     NUMBER(19) NOT NULL,
                               doc_type    VARCHAR2(30) NOT NULL,
                               doc_number  VARCHAR2(100) NOT NULL,
                               status      VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
                               uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               CONSTRAINT fk_kyc_user FOREIGN KEY (user_id) REFERENCES users(id)
);