CREATE TABLE cards (
                          id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          wallet_id     NUMBER(19) NOT NULL,
                          masked_number VARCHAR2(25) NOT NULL,
                          last4        VARCHAR2(4) NOT NULL,
                          expiry_month NUMBER(2) NOT NULL,
                          expiry_year  NUMBER(4) NOT NULL,
                          type        VARCHAR2(20) NOT NULL,
                          status      VARCHAR2(20) NOT NULL,
                          created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
